### ISSUE TITLE
Newbie error at packaging?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#284]
Hello once again!

```
I decided to make my app as installation because it had too many files (~3100) and the launch time became quite a pain for the user.
```

I did a package using advanced options set to true and voala! I got a brand new installer.
Then I installed the app in a chosen directory.
Then... launched the app from the desktop shortcut. The app launched but it was mostly grey screen.
The console says that the code cannot find the images that the app uses for background.

I went in the app directory and launched the app directly from the script - Everything was working.
Tried lanching it from the exe in the app folder - again the app could not find the images.

I assume this is issue with the relative paths in the app but why is it happening? Do I do something wrong?

p.s.
Packaging and testing is both done on windows. Packaging is done through the cmd as advised.

**Comment by ccoupe** [comment]
Packaging won't fix the number of files seen by the Shoes app. Advanced packaging is for patient people who can debug some very dense code (their own installer srcript). Start simple, just use the simple download if needed and see if that works on a system that _doesn't have_ shoes installed. Packaging is mostly about installing Shoes and then your code.

**Comment by ccoupe** [comment]
Windows is pain in the behind.  The current working directory is probably where the Shoes.exe is, which is not where your packaged app (and files are);  or vice versa. Calling  Dir.getwd  returns the full path so I append to that.

**Comment by dredknight** [comment]
Thanks Cecil.

Actually the problem is not in having system with Shoes or not it is in the SHY file itself. It is really slow due to the number of files. With the secondary installer all files are fully unpacked so it works instantly.

I will try to work on the installer script and see if I can get any interesting stuff.

**Comment by ccoupe** [comment]
A shy unpacks into a temp dir, every time the shy is run and with your number of files, that would add some visible delay to startup.  Windows 10 has pretty much killed Shoes packaging. It's a lot more work for you but my  [exe-shoes](https://github.com/Shoes3/exe-shoes) really is the best way for what most  Windows (and MSFT) think of for packaging.

**Comment by dredknight** [comment]
Splendid! I will try it out!

**Comment by dredknight** [comment]
Alright I started working on that exe thing. I pretty much get what is required but what I dont understand is why when I do a test launch I get error for shoes version 2.2 ?

```CMD
C:\Users\dredknight>cd Desktop\shoes\exe-shoes-master

C:\Users\dredknight\Desktop\shoes\exe-shoes-master>cd Desktop\shoes\exe-shoes-ma
ster

C:\Users\dredknight\Desktop\shoes\exe-shoes-master>cshoes.exe --ruby ytm-merge.r
b
DIR = C:/Program Files (x86)/Shoes
GEMS_DIR = C:/Users/dredknight/AppData/Local/Shoes/+gem
Here = C:/Users/dredknight/Desktop/shoes/exe-shoes-master
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb:1450:in `unlink': No su
ch file or directory @ unlink_internal - packdir/lib/shoes/irb.rb (Errno::ENOENT
)
        from C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb:1450:in `b
lock in remove_file'
        from C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb:1458:in `p
latform_support'
        from C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb:1449:in `r
emove_file'
        from C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb:793:in `re
move_file'
        from C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb:571:in `bl
ock in rm'
        from C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb:570:in `ea
ch'
        from C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb:570:in `rm
'
        from C:/Users/dredknight/Desktop/shoes/exe-shoes-master/merge-exe.rb:68:
in `block in merge_exe'
        from C:/Users/dredknight/Desktop/shoes/exe-shoes-master/merge-exe.rb:68:
in `each'
        from C:/Users/dredknight/Desktop/shoes/exe-shoes-master/merge-exe.rb:68:
in `merge_exe'
        from ytm-merge.rb:13:in `<main>'

```

**Comment by ccoupe** [comment]
do mean ruby 2.2.0 ?    hkey_org is something that the install script needs to be msft registry happy. If you have your own domain name, use it instead of mine. if you don't have a domain, you can use mine - I'll never know. 

That error message doesn't look good. You should have the file, irb.rb that it says is missing.

**Comment by dredknight** [comment]
alright alright yes you are correct it is ruby not shoes.
but that IRB error... from what I see packdir is where all the stuff are poured and packed.
For some reason packdir/lib/shoes/irb.rb which is related to the Shoes package is not there while all other libs are there. 

Also it seems that IRB is not required as later in the merge-exe.rb parchment the following lines are found:

```Ruby
 # remove unreachable code in packdir/lib/shoes/ like help, app-package ...
    ['cobbler', 'debugger', 'irb', 'pack', 'app_package', 'packshoes',
      'remote_debugger', 'winject', 'envgem'].each {|f| rm "#{packdir}/lib/shoes/#{f}.rb" }
```
This means that IRB.rb is not required at all...

**Comment by ccoupe** [comment]
Correct - it's not used in the merged exe but it should have been copied there from the original Shoes.

**Comment by ccoupe** [comment]
> C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb:1450:in `unlink

your yaml file settings aren't correct  enough. Your appear to be deleting for Shoes instead of copying shoes to a new place and delete the unwanted from that. Please post your .yaml.

**Comment by dredknight** [comment]
Here you are

```YAML
app_name: Ytm
app_version: 'Demo'
app_loc: C:/Users/dredknight/Desktop/shoes/exe-shoes-master/ytm
app_start: ytm.rb
app_png: ytm.png
app_ico: C:/Users/dredknight/Desktop/shoes/exe-shoes-master/ytm/ytm.ico
app_installer_ico: C:/Users/dredknight/Desktop/shoes/exe-shoes-master/ytm/ytm.ico
installer_sidebar_bmp: C:/Users/dredknight/Desktop/shoes/exe-shoes-master/nsis/installer-1.bmp
installer_header_bmp: C:/Users/dredknight/Desktop/shoes/exe-shoes-master/nsis/installer-2.bmp
publisher: 'www.heroescommunity.com'
website: 'http://heroescommunity.com/viewthread.php3?TID=42212'
hkey_org: 'mvmanila.com'
license: C:/Users/dredknight/Desktop/shoes/exe-shoes-master/ytm/Ytm.license
include_exts:
 - ftsearch
 - chipmunk
include_gems:
 - sqlite3
 - nokogiri-1.6.7.1-x86-mingw32
 - ffi-1.9.10-x86-mingw32
 - rubyserial-0.2.4
```
